# Generated by Django 4.2.18 on 2025-03-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("record", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "不具合"), (1, "タスク"), (2, "要望"), (3, "その他")]
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Record",
        ),
    ]
