# Generated by Django 4.2.18 on 2025-03-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0002_issues_delete_record"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issues",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="issues",
            name="date",
        ),
        migrations.AddField(
            model_name="issues",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issues",
            name="date_of_update",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="issues",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issues",
            name="person",
            field=models.IntegerField(
                choices=[(0, "担当A"), (1, "担当B"), (2, "担当C"), (3, "担当D")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issues",
            name="progress",
            field=models.IntegerField(
                choices=[(0, "完了"), (1, "進行中"), (2, "未対応"), (3, "保留"), (4, "対応不要")],
                default=2,
            ),
            preserve_default=False,
        ),
    ]
