# Generated by Django 4.2.18 on 2025-03-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0003_remove_issues_amount_remove_issues_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issues",
            name="contents",
            field=models.TextField(blank=True, null=True),
        ),
    ]
