# Generated by Django 4.2.18 on 2025-03-24 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0004_issues_contents"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issues",
            old_name="record",
            new_name="progress_details",
        ),
    ]
