# Generated by Django 4.2.18 on 2025-04-05 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0006_rename_progress_details_issues_progress_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issues",
            name="progress_comment",
        ),
    ]
