# Generated by Django 4.2.18 on 2025-04-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issue", "0007_remove_issues_progress_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
