# Generated by Django 4.2.18 on 2025-04-08 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0008_alter_issues_person_alter_issues_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progresscomment",
            name="issues",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="issue.issues"
            ),
        ),
    ]
