# Generated by Django 4.2.18 on 2025-04-11 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0010_alter_issues_person_alter_progresscomment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progresscomment",
            old_name="issues",
            new_name="target",
        ),
    ]
