# Generated by Django 4.2.18 on 2025-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0011_rename_issues_progresscomment_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progresscomment",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="progresscomment",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
