# Generated by Django 4.2.18 on 2025-04-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0012_alter_progresscomment_create_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="file/%Y/%m/%d/")),
            ],
        ),
        migrations.AlterModelOptions(
            name="progresscomment",
            options={"ordering": ["-create_date"]},
        ),
    ]
