# Generated by Django 4.2.18 on 2025-04-23 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0013_document_alter_progresscomment_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="file",
            new_name="upload",
        ),
    ]
