# Generated by Django 4.2.18 on 2025-05-09 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0015_attachment_item_delete_document_attachment_item"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="UploadFile",
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
