# Generated by Django 4.2.18 on 2025-05-09 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0016_rename_item_uploadfile_delete_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
