# Generated by Django 4.2.18 on 2025-05-09 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0017_uploadfile_uploaded_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progresscomment",
            old_name="target",
            new_name="issues",
        ),
    ]
