# Generated by Django 4.2.18 on 2025-05-09 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0018_rename_target_progresscomment_issues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadfile",
            name="description",
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="uploads/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="issue",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="issue.issues",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uploadfile",
            name="title",
            field=models.CharField(max_length=50, verbose_name="ファイル名"),
        ),
    ]
